/**
 * DSRV validator partners data.
 * Update delegation, aprPercent, commissionPercent, uptime from each chain's explorer.
 * Delegation amounts are in native token units.
 * Run scripts/sync.js every 2 weeks to refresh prices + snapshot delegation.
 */
const PARTNERS = [
  // ── Ethereum ecosystem ──
  { name: "Etherfi (total)", delegationAmount: 288288, tokenSymbol: "ETH", coingeckoId: "ethereum", aprPercent: 3.5, commissionPercent: 10, explorerDelegation: "https://explorer.rated.network/o/DSRV%20-%20Ether.Fi?network=mainnet&timeWindow=1d&idType=poolShare", explorerUptime: "https://explorer.rated.network/o/DSRV%20-%20Ether.Fi?network=mainnet&timeWindow=1d&idType=poolShare", uptimePercent: null },
  { name: "Lido (total)", delegationAmount: 249440, tokenSymbol: "stETH", coingeckoId: "staked-ether", aprPercent: 3.2, commissionPercent: 10, explorerDelegation: "https://explorer.rated.network/o/DSRV%20-%20Lido?network=mainnet&timeWindow=1d&idType=poolShare", explorerUptime: "https://explorer.rated.network/o/DSRV%20-%20Lido?network=mainnet&timeWindow=1d&idType=poolShare", uptimePercent: null },
  { name: "Swell", delegationAmount: 2688, tokenSymbol: "SWELL", coingeckoId: "swell-ethereum", aprPercent: 3.2, commissionPercent: 10, explorerDelegation: "https://explorer.rated.network/o/DSRV%20-%20Swell?network=mainnet&timeWindow=1d&idType=poolShare", explorerUptime: "https://explorer.rated.network/o/DSRV%20-%20Swell?network=mainnet&timeWindow=1d&idType=poolShare", uptimePercent: null },
  { name: "StakeWise (ETH)", delegationAmount: null, tokenSymbol: "ETH", coingeckoId: "ethereum", aprPercent: 3.2, commissionPercent: 10, explorerDelegation: "https://app.stakewise.io/vault/mainnet/0xea6db44b0d7e20f72f2b4b3deaaa9e710e718bd9", explorerUptime: "https://app.stakewise.io/vault/mainnet/0xea6db44b0d7e20f72f2b4b3deaaa9e710e718bd9", uptimePercent: null },
  { name: "EigenLayer", delegationAmount: null, tokenSymbol: "EIGEN", coingeckoId: "eigenlayer", aprPercent: null, commissionPercent: null, explorerDelegation: "https://app.eigenlayer.xyz/operator/0xdcae4faf7c7d0f4a78abe147244c6e9d60cfd202", explorerUptime: "https://app.eigenlayer.xyz/operator/0x5b9b3cf0202a1a3dc8f527257b7e6002d23d8c85", uptimePercent: null },

  // ── L1 chains ──
  { name: "Solana", delegationAmount: 24983, tokenSymbol: "SOL", coingeckoId: "solana", aprPercent: 6.5, commissionPercent: 8, explorerDelegation: "https://stakewiz.com/validator/2mxWiqtwdpE8zgkWxwFaJLn127dbuuHY4D32d8A6UnPL", explorerUptime: "https://www.validators.app/validators/DSRVdh9PQaqAcFtMCbJhyD4yMD5H2EeHNzdbqWctRY4E", uptimePercent: null },
  { name: "Sui", delegationAmount: 135558249, tokenSymbol: "SUI", coingeckoId: "sui", aprPercent: 4.2, commissionPercent: 10, explorerDelegation: "https://suivision.xyz/validator/0x6f4e73ee97bfae95e054d31dff1361a839aaadf2cfdb873ad2b07d479507905a", explorerUptime: "https://suiscan.xyz/mainnet/validator/0x6f4e73ee97bfae95e054d31dff1361a839aaadf2cfdb873ad2b07d479507905a/info", uptimePercent: null },
  { name: "Aptos (total)", delegationAmount: 4291607, tokenSymbol: "APT", coingeckoId: "aptos", aprPercent: 6.8, commissionPercent: 10, explorerDelegation: "https://explorer.aptoslabs.com/validator/0xee36c1068076b199cf537bf652b1e586216a7dfb7c3447ff40333c971717eee6?network=mainnet", explorerUptime: "https://aptoscan.com/account/0x371dfdee9fbecaa358683936c5946aa28393067fa60e1e185c4250da461e15cf", uptimePercent: null },
  { name: "Near", delegationAmount: 2073326, tokenSymbol: "NEAR", coingeckoId: "near", aprPercent: 9, commissionPercent: 10, explorerDelegation: "https://nearscope.net/validator/dsrvlabs.poolv1.near/tab/dashboard", explorerUptime: "https://nearblocks.io/node-explorer/dsrvlabs.poolv1.near", uptimePercent: null },
  { name: "Avalanche", delegationAmount: null, tokenSymbol: "AVAX", coingeckoId: "avalanche-2", aprPercent: 8, commissionPercent: 10, explorerDelegation: "https://avascan.info/staking/validator/NodeID-BcfnNieXDpsvkMApb8FcCmGAoQdtyu8jH", explorerUptime: "https://avascan.info/staking/validator/NodeID-BcfnNieXDpsvkMApb8FcCmGAoQdtyu8jH", uptimePercent: null },
  { name: "Mina", delegationAmount: null, tokenSymbol: "MINA", coingeckoId: "mina-protocol", aprPercent: 12, commissionPercent: 5, explorerDelegation: "https://minaexplorer.com/wallet/B62qp8Vq6n4VHq1LUm9Wd5QKjpKb7umoZ2oU9gpJYuHNUc7t2HGhGUA", explorerUptime: "https://minaexplorer.com/wallet/B62qp8Vq6n4VHq1LUm9Wd5QKjpKb7umoZ2oU9gpJYuHNUc7t2HGhGUA", uptimePercent: null },
  { name: "Aleo", delegationAmount: null, tokenSymbol: "ALEO", coingeckoId: "aleo", aprPercent: null, commissionPercent: null, explorerDelegation: "https://vxb.ai/address/aleo1dsrv0z6wu9mgzl5l7wh62rwmrd4yt3zva7n4ayhvg02luvtqkqgq5tw209", explorerUptime: "https://vxb.ai/address/aleo1dsrv0z6wu9mgzl5l7wh62rwmrd4yt3zva7n4ayhvg02luvtqkqgq5tw209", uptimePercent: null },
  { name: "Monad", delegationAmount: 59240000, tokenSymbol: "MON", coingeckoId: "monad", aprPercent: null, commissionPercent: null, explorerDelegation: "https://monadvision.com/validator/0x4a27964A705C3739d742831B1577900735F9547f", explorerUptime: "https://monadvision.com/validator/0x4a27964A705C3739d742831B1577900735F9547f", uptimePercent: null },
  { name: "Supra", delegationAmount: 63561586, tokenSymbol: "SUPRA", coingeckoId: "supra", aprPercent: null, commissionPercent: null, explorerDelegation: "https://suprascan.io/address/0x4394f0b524832e01a6ffce798eee9b13ff5fd2a6bd11f9c57de908746faf94e8/f?tab=resources", explorerUptime: "https://suprascan.io/address/0x4394f0b524832e01a6ffce798eee9b13ff5fd2a6bd11f9c57de908746faf94e8/f?tab=resources", uptimePercent: null },
  { name: "Canton", delegationAmount: null, delegationNote: "NaaS Provider & Mainnet Validator", tokenSymbol: "CC", coingeckoId: "canton-network", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.cantonscan.com/party/dsrv-mainnetValidator-01%3A%3A1220e2f4abe1c5ca7e07464037fe7fefc839b7b8fea24985d0d2a2790fa72e3c13ac", explorerUptime: "https://www.cantonscan.com/party/dsrv-mainnetValidator-01%3A%3A1220e2f4abe1c5ca7e07464037fe7fefc839b7b8fea24985d0d2a2790fa72e3c13ac", uptimePercent: null },
  { name: "Starknet", delegationAmount: null, tokenSymbol: "STRK", coingeckoId: "starknet", aprPercent: null, commissionPercent: null, explorerDelegation: "https://voyager.online/staking?validator=0x03ba5c922cc9bbde55a41d51c2eba6027c653da318f1956c2405d42451d8e3a8", explorerUptime: "https://voyager.online/staking?validator=0x03ba5c922cc9bbde55a41d51c2eba6027c653da318f1956c2405d42451d8e3a8", uptimePercent: null },

  // ── Cosmos ecosystem ──
  { name: "Babylon", delegationAmount: 56175134, tokenSymbol: "BABY", coingeckoId: "babylon", aprPercent: null, commissionPercent: 10, explorerDelegation: "https://www.mintscan.io/babylon/validators/bbnvaloper18hly9zagjfuzzeqp92uhwafmplmtgd0u98vjj3", explorerUptime: "https://www.mintscan.io/babylon/finality-providers/086fe422ec074cb64d7b06eeca4bf985f532eb32dcf8172402b5cb604d7c9a29", uptimePercent: null },
  { name: "Satlayer (Babylon)", delegationAmount: null, tokenSymbol: "BABY", coingeckoId: "babylon", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.mintscan.io/babylon/validators/bbnvaloper18hly9zagjfuzzeqp92uhwafmplmtgd0u98vjj3", explorerUptime: "https://www.mintscan.io/babylon/validators/bbnvaloper18hly9zagjfuzzeqp92uhwafmplmtgd0u98vjj3", uptimePercent: null },
  { name: "Celestia", delegationAmount: 5864641, tokenSymbol: "TIA", coingeckoId: "celestia", aprPercent: 12, commissionPercent: 8, explorerDelegation: "https://www.mintscan.io/celestia/validators/celestiavaloper1vje2he3pcq3w5udyvla7zm9qd5yes6hzffsjxj/", explorerUptime: "https://www.mintscan.io/celestia/validators/celestiavaloper1vje2he3pcq3w5udyvla7zm9qd5yes6hzffsjxj/", uptimePercent: null },
  { name: "Cosmos HUB", delegationAmount: 190927, tokenSymbol: "ATOM", coingeckoId: "cosmos", aprPercent: 11, commissionPercent: 8, explorerDelegation: "https://www.mintscan.io/cosmos/validators/cosmosvaloper1wlagucxdxvsmvj6330864x8q3vxz4x02rmvmsu/", explorerUptime: "https://www.mintscan.io/cosmos/validators/cosmosvaloper1wlagucxdxvsmvj6330864x8q3vxz4x02rmvmsu/", uptimePercent: null },
  { name: "AtomOne", delegationAmount: null, tokenSymbol: "ATONE", coingeckoId: "atomone", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.mintscan.io/atomone/validators/atonevaloper1wlagucxdxvsmvj6330864x8q3vxz4x022j0qq0/", explorerUptime: "https://www.mintscan.io/atomone/validators/atonevaloper1wlagucxdxvsmvj6330864x8q3vxz4x022j0qq0/", uptimePercent: null },
  { name: "Osmosis", delegationAmount: 3776503, tokenSymbol: "OSMO", coingeckoId: "osmosis", aprPercent: 12, commissionPercent: 5, explorerDelegation: "https://www.mintscan.io/osmosis/validators/osmovaloper1wlagucxdxvsmvj6330864x8q3vxz4x025rraa6/", explorerUptime: "https://www.mintscan.io/osmosis/validators/osmovaloper1wlagucxdxvsmvj6330864x8q3vxz4x025rraa6/", uptimePercent: null },
  { name: "Axelar", delegationAmount: 5504221, tokenSymbol: "AXL", coingeckoId: "axelar", aprPercent: 9, commissionPercent: 8, explorerDelegation: "https://www.mintscan.io/axelar/validators/axelarvaloper137nzwehjcjxddsanmsmg29p729cm4dghj08clr/", explorerUptime: "https://www.mintscan.io/axelar/validators/axelarvaloper137nzwehjcjxddsanmsmg29p729cm4dghj08clr/", uptimePercent: null },
  { name: "Shentu", delegationAmount: 1080425, tokenSymbol: "CTK", coingeckoId: "shentu", aprPercent: 10, commissionPercent: 8, explorerDelegation: "https://www.mintscan.io/shentu/validators/shentuvaloper1vgpzxfmw8up2gugglj50t2uddlpd5shdu49c8g/", explorerUptime: "https://www.mintscan.io/shentu/validators/shentuvaloper1vgpzxfmw8up2gugglj50t2uddlpd5shdu49c8g/", uptimePercent: null },
  { name: "Archway", delegationAmount: null, tokenSymbol: "ARCH", coingeckoId: "archway", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.mintscan.io/archway/validators/archwayvaloper1zttnm2cl60m5ffsrfeqtzkmtvepl4hwndvgtka/", explorerUptime: "https://www.mintscan.io/archway/validators/archwayvaloper1zttnm2cl60m5ffsrfeqtzkmtvepl4hwndvgtka/", uptimePercent: null },
  { name: "Agoric", delegationAmount: null, tokenSymbol: "BLD", coingeckoId: "agoric", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.mintscan.io/agoric/validators/agoricvaloper1wlagucxdxvsmvj6330864x8q3vxz4x02y2fcsc/", explorerUptime: "https://www.mintscan.io/agoric/validators/agoricvaloper1wlagucxdxvsmvj6330864x8q3vxz4x02y2fcsc/", uptimePercent: null },
  { name: "Persistence", delegationAmount: null, tokenSymbol: "XPRT", coingeckoId: "persistence", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.mintscan.io/persistence/validators/persistencevaloper1d0xdy0v97grs8ru8nccqyzyc9l8ppv0zv6p5xg/", explorerUptime: "https://www.mintscan.io/persistence/validators/persistencevaloper1d0xdy0v97grs8ru8nccqyzyc9l8ppv0zv6p5xg/", uptimePercent: null },
  { name: "XPLA", delegationAmount: null, tokenSymbol: "XPLA", coingeckoId: "xpla", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.mintscan.io/xpla/validators/xplavaloper18nwzp4g297pvq9kv6exzrlwx23tqpsfxnp3yyd/", explorerUptime: "https://www.mintscan.io/xpla/validators/xplavaloper18nwzp4g297pvq9kv6exzrlwx23tqpsfxnp3yyd/", uptimePercent: null },
  { name: "Chihuahua", delegationAmount: null, tokenSymbol: "HUAHUA", coingeckoId: "chihuahua-token", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.mintscan.io/chihuahua/validators/chihuahuavaloper128jw67hyqd02zxeqeqzy4dzfx67g3dplwqlqjl/", explorerUptime: "https://www.mintscan.io/chihuahua/validators/chihuahuavaloper128jw67hyqd02zxeqeqzy4dzfx67g3dplwqlqjl/", uptimePercent: null },
  { name: "Zeta", delegationAmount: null, tokenSymbol: "ZETA", coingeckoId: "zetachain", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.mintscan.io/zeta/validators/zetavaloper1txfmxp4d9dc9wqa2f7wvqed9635zajn0hrmz8z/", explorerUptime: "https://www.mintscan.io/zeta/validators/zetavaloper1txfmxp4d9dc9wqa2f7wvqed9635zajn0hrmz8z/", uptimePercent: null },
  { name: "Xion", delegationAmount: null, tokenSymbol: "XION", coingeckoId: "xion-2", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.mintscan.io/xion/validators/xionvaloper1ddqn26gh4kqeta6h7mcpt6sf0ww5r2kclajve5/", explorerUptime: "https://www.mintscan.io/xion/validators/xionvaloper1ddqn26gh4kqeta6h7mcpt6sf0ww5r2kclajve5/", uptimePercent: null },
  { name: "Provenance (Figure)", delegationAmount: 200012050, tokenSymbol: "HASH", coingeckoId: "hash-2", aprPercent: 8, commissionPercent: 10, explorerDelegation: "https://www.mintscan.io/provenance/validators/pbvaloper1s9f4e20xtqrk9tdfhhpavrf26cqjr4eyt3yjqg", explorerUptime: "https://www.mintscan.io/provenance/validators/pbvaloper1s9f4e20xtqrk9tdfhhpavrf26cqjr4eyt3yjqg", uptimePercent: null },
  { name: "Lava", delegationAmount: null, tokenSymbol: "LAVA", coingeckoId: "lava-network", aprPercent: null, commissionPercent: null, explorerDelegation: "https://lava-explorer.w3coins.io/Lava/staking/lava@valoper1zwwfezfnjxtfxe90c4c6v6rkk24eqmyz9lhx5l", explorerUptime: "https://lava-explorer.w3coins.io/Lava/staking/lava@valoper1zwwfezfnjxtfxe90c4c6v6rkk24eqmyz9lhx5l", uptimePercent: null },
  { name: "Stride", delegationAmount: null, tokenSymbol: "STRD", coingeckoId: "stride", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.stakingrewards.com/asset/stride", explorerUptime: "https://www.stakingrewards.com/asset/stride", uptimePercent: null },
  { name: "Stargaze", delegationAmount: null, tokenSymbol: "STARS", coingeckoId: "stargaze", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.stakingrewards.com/asset/stargaze", explorerUptime: "https://www.stakingrewards.com/asset/stargaze", uptimePercent: null },
  { name: "AssetMantle", delegationAmount: null, tokenSymbol: "MNTL", coingeckoId: "assetmantle", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.stakingrewards.com/asset/asset-mantle", explorerUptime: "https://www.stakingrewards.com/asset/asset-mantle", uptimePercent: null },
  { name: "Umee", delegationAmount: null, tokenSymbol: "UX", coingeckoId: "umee", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.stakingrewards.com/asset/umee", explorerUptime: "https://www.stakingrewards.com/asset/umee", uptimePercent: null },
  { name: "KYVE", delegationAmount: null, tokenSymbol: "KYVE", coingeckoId: "kyve-network", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.stakingrewards.com/asset/kyve-network", explorerUptime: "https://www.stakingrewards.com/asset/kyve-network", uptimePercent: null },

  // ── Other L1/L2 chains ──
  { name: "0G", delegationAmount: 3000548, tokenSymbol: "0G", coingeckoId: "0g", aprPercent: null, commissionPercent: null, explorerDelegation: "https://explorer.0g.ai/mainnet/validators/0x7840481938247e47db1488c033e8d18a21c85cfd/delegators", explorerUptime: "https://explorer.0g.ai/mainnet/validators/0x7840481938247e47db1488c033e8d18a21c85cfd/delegators", uptimePercent: null },
  { name: "IOTA", delegationAmount: 47958203, tokenSymbol: "IOTA", coingeckoId: "iota", aprPercent: 8, commissionPercent: 10, explorerDelegation: "https://iotascan.com/mainnet/validator/0xb7c4b7a63c1dd642d2d220630ca3ebf028c7a9ce8308a61bea75c169d21d611b/info", explorerUptime: "https://explorer.iota.org/validator/0xb7c4b7a63c1dd642d2d220630ca3ebf028c7a9ce8308a61bea75c169d21d611b", uptimePercent: null },
  { name: "Story", delegationAmount: 7256548, tokenSymbol: "IP", coingeckoId: "story-protocol", aprPercent: null, commissionPercent: null, explorerDelegation: "https://story.explorers.guru/validator/storyvaloper1pjhn2l646wdphwjw4jkumsa4w4jsezu7nth4dm", explorerUptime: "https://ipworld.io/validators", uptimePercent: null },
  { name: "Plume", delegationAmount: 2556993, tokenSymbol: "PLUME", coingeckoId: "plume", aprPercent: null, commissionPercent: null, explorerDelegation: "https://staking.plume.org/", explorerUptime: "https://staking.plume.org/", uptimePercent: null },
  { name: "Polygon", delegationAmount: 118087, tokenSymbol: "POL", coingeckoId: "polygon-ecosystem-token", aprPercent: 4.5, commissionPercent: 10, explorerDelegation: "https://staking.polygon.technology/validators/64", explorerUptime: "https://staking.polygon.technology/validators/64", uptimePercent: null },
  { name: "Wemix", delegationAmount: 1505357, tokenSymbol: "WEMIX", coingeckoId: "wemix-token", aprPercent: 6, commissionPercent: 10, explorerDelegation: "https://wemixstake.com/ko/staking/wonder", explorerUptime: "https://wemixstake.com/ko/staking/wonder", uptimePercent: null },
  { name: "IKA", delegationAmount: 62091780, tokenSymbol: "IKA", coingeckoId: "ika", aprPercent: null, commissionPercent: null, explorerDelegation: "https://ikascan.io/mainnet/operator/0x1070423a19ad7097768e8da8d1f2e36663f898bfaeb8325dbb643366bdbf8717", explorerUptime: "https://ikascan.io/mainnet/operator/0x1070423a19ad7097768e8da8d1f2e36663f898bfaeb8325dbb643366bdbf8717", uptimePercent: null },
  { name: "Mitosis", delegationAmount: 900001, tokenSymbol: "MITO", coingeckoId: "mitosis", aprPercent: null, commissionPercent: null, explorerDelegation: "https://app.mitosis.org/staking/validator/0xc0cccda718572b80d804214596a7bff1b96064b4", explorerUptime: "https://app.mitosis.org/staking/validator/0xc0cccda718572b80d804214596a7bff1b96064b4", uptimePercent: null },
  { name: "Namada", delegationAmount: 2257929, tokenSymbol: "NAM", coingeckoId: "namada", aprPercent: 14, commissionPercent: 8, explorerDelegation: "https://namada.valopers.com/validators/tnam1q9vjuxuwdv9muek3ekvvjfngyt973agg2c5c7hxp", explorerUptime: "https://namada.info/validators", uptimePercent: null },
  { name: "Initia", delegationAmount: null, tokenSymbol: "INIT", coingeckoId: "initia", aprPercent: null, commissionPercent: null, explorerDelegation: "https://scan.initia.xyz/interwoven-1/validators/initvaloper1mfg2ssl4m0tgf7dctl6uddeg0xmwg6a3506kds", explorerUptime: "https://scan.initia.xyz/interwoven-1/validators/initvaloper1mfg2ssl4m0tgf7dctl6uddeg0xmwg6a3506kds", uptimePercent: null },
];

const DATA_DATE = "2026-02-23";
