/**
 * DSRV validator partners data.
 * Update delegation, aprPercent, commissionPercent, uptime from each chain's explorer.
 * Uptime %: fill from the "Uptime" link column (search for DSRV on that page).
 */
const PARTNERS = [
  { name: "Canton", delegationAmount: null, delegationNote: "NaaS Provider & Mainnet Validator", tokenSymbol: "CANTON", coingeckoId: null, aprPercent: null, commissionPercent: null, explorerDelegation: null, explorerUptime: null, uptimePercent: null },
  { name: "Etherfi (total)", delegationAmount: 288288, tokenSymbol: "ETH", coingeckoId: "ethereum", aprPercent: 3.5, commissionPercent: 10, explorerDelegation: "https://ether.fi/dashboard", explorerUptime: "https://beaconcha.in/", uptimePercent: null },
  { name: "Lido (total)", delegationAmount: 249440, tokenSymbol: "stETH", coingeckoId: "staked-ether", aprPercent: 3.2, commissionPercent: 10, explorerDelegation: "https://lido.fi/", explorerUptime: "https://beaconcha.in/", uptimePercent: null },
  { name: "Solana", delegationAmount: 24983, tokenSymbol: "SOL", coingeckoId: "solana", aprPercent: 6.5, commissionPercent: 8, explorerDelegation: "https://www.validators.app/validators?locale=en&network=mainnet", explorerUptime: "https://www.validators.app/validators?locale=en&network=mainnet", uptimePercent: null },
  { name: "0G", delegationAmount: 3000548, tokenSymbol: "ZRO", coingeckoId: null, aprPercent: null, commissionPercent: null, explorerDelegation: "https://explorer.0g.ai/mainnet/validators", explorerUptime: "https://explorer.0g.ai/mainnet/validators", uptimePercent: null },
  { name: "Sui", delegationAmount: 135558249, tokenSymbol: "SUI", coingeckoId: "sui", aprPercent: 4.2, commissionPercent: 10, explorerDelegation: "https://suiexplorer.com/validators", explorerUptime: "https://suiexplorer.com/validators", uptimePercent: null },
  { name: "Aptos (total)", delegationAmount: 4291607, tokenSymbol: "APT", coingeckoId: "aptos", aprPercent: 6.8, commissionPercent: 10, explorerDelegation: "https://explorer.aptoslabs.com/validators", explorerUptime: "https://explorer.aptoslabs.com/validators", uptimePercent: null },
  { name: "Babylon", delegationAmount: 56175134, tokenSymbol: "BABY", coingeckoId: null, aprPercent: null, commissionPercent: 10, explorerDelegation: "https://babylon.explorers.guru/validators", explorerUptime: "https://babylon.explorers.guru/validators", uptimePercent: null },
  { name: "Satlayer (Babylon)", delegationAmount: null, tokenSymbol: "BABY", coingeckoId: null, aprPercent: null, commissionPercent: null, explorerDelegation: "https://babylon.explorers.guru/validators", explorerUptime: "https://babylon.explorers.guru/validators", uptimePercent: null },
  { name: "Celestia", delegationAmount: 5864641, tokenSymbol: "TIA", coingeckoId: "celestia", aprPercent: 12, commissionPercent: 8, explorerDelegation: "https://www.mintscan.io/celestia/validators", explorerUptime: "https://celestia.explorers.guru/validators", uptimePercent: null },
  { name: "IOTA", delegationAmount: 47958203, tokenSymbol: "IOTA", coingeckoId: "iota", aprPercent: 8, commissionPercent: 10, explorerDelegation: "https://iotascan.com/validators", explorerUptime: "https://iotascan.com/validators", uptimePercent: null },
  { name: "Near", delegationAmount: 2073326, tokenSymbol: "NEAR", coingeckoId: "near", aprPercent: 9, commissionPercent: 10, explorerDelegation: "https://nearblocks.io/validators", explorerUptime: "https://nearblocks.io/validators", uptimePercent: null },
  { name: "Story", delegationAmount: 7256548, tokenSymbol: "IP", coingeckoId: "story-protocol", aprPercent: null, commissionPercent: null, explorerDelegation: "https://www.storyscan.xyz/", explorerUptime: "https://www.storyscan.xyz/", uptimePercent: null },
  { name: "Plume", delegationAmount: 2556993, tokenSymbol: "PLUME", coingeckoId: null, aprPercent: null, commissionPercent: null, explorerDelegation: null, explorerUptime: null, uptimePercent: null },
  { name: "Polygon", delegationAmount: 118087, tokenSymbol: "POL", coingeckoId: "polygon-ecosystem-token", aprPercent: 4.5, commissionPercent: 10, explorerDelegation: "https://staking.polygon.technology/validators", explorerUptime: "https://staking.polygon.technology/validators", uptimePercent: null },
  { name: "Wemix", delegationAmount: 1505357, tokenSymbol: "WEMIX", coingeckoId: "wemix-token", aprPercent: 6, commissionPercent: 10, explorerDelegation: null, explorerUptime: null, uptimePercent: null },
  { name: "Swell", delegationAmount: 2688, tokenSymbol: "SWELL", coingeckoId: "swell-ethereum", aprPercent: 3.2, commissionPercent: 10, explorerDelegation: "https://swellnetwork.io/", explorerUptime: "https://beaconcha.in/", uptimePercent: null },
  { name: "IKA", delegationAmount: 62091780, tokenSymbol: "IKA", coingeckoId: null, aprPercent: null, commissionPercent: null, explorerDelegation: null, explorerUptime: null, uptimePercent: null },
  { name: "Shentu", delegationAmount: 1080425, tokenSymbol: "CTK", coingeckoId: "shentu", aprPercent: 10, commissionPercent: 8, explorerDelegation: "https://www.mintscan.io/shentu/validators", explorerUptime: "https://www.mintscan.io/shentu/validators", uptimePercent: null },
  { name: "Axelar", delegationAmount: 5504221, tokenSymbol: "AXL", coingeckoId: "axelar", aprPercent: 9, commissionPercent: 8, explorerDelegation: "https://www.mintscan.io/axelar/validators", explorerUptime: "https://www.mintscan.io/axelar/validators", uptimePercent: null },
  { name: "Cosmos HUB", delegationAmount: 190927, tokenSymbol: "ATOM", coingeckoId: "cosmos", aprPercent: 11, commissionPercent: 8, explorerDelegation: "https://www.mintscan.io/cosmos/validators", explorerUptime: "https://www.mintscan.io/cosmos/validators", uptimePercent: null },
  { name: "Mitosis", delegationAmount: 900001, tokenSymbol: "MTS", coingeckoId: null, aprPercent: null, commissionPercent: null, explorerDelegation: null, explorerUptime: null, uptimePercent: null },
  { name: "Namada", delegationAmount: 2257929, tokenSymbol: "NAM", coingeckoId: "namada", aprPercent: 14, commissionPercent: 8, explorerDelegation: "https://namada.explorers.guru/validators", explorerUptime: "https://namada.explorers.guru/validators", uptimePercent: null },
  { name: "Monad", delegationAmount: 59240000, tokenSymbol: "MON", coingeckoId: null, aprPercent: null, commissionPercent: null, explorerDelegation: null, explorerUptime: null, uptimePercent: null },
  { name: "Supra", delegationAmount: 63561586, tokenSymbol: "SUPRA", coingeckoId: null, aprPercent: null, commissionPercent: null, explorerDelegation: null, explorerUptime: null, uptimePercent: null },
  { name: "Osmosis", delegationAmount: 3776503, tokenSymbol: "OSMO", coingeckoId: "osmosis", aprPercent: 12, commissionPercent: 5, explorerDelegation: "https://www.mintscan.io/osmosis/validators", explorerUptime: "https://osmosis.explorers.guru/validators", uptimePercent: null },
  { name: "Provenance (Figure)", delegationAmount: 200012050, tokenSymbol: "HASH", coingeckoId: "hash-2", aprPercent: 8, commissionPercent: 10, explorerDelegation: "https://explorer.provenance.io/validators", explorerUptime: "https://explorer.provenance.io/validators", uptimePercent: null }
];

const DATA_DATE = "2026-02-23";
